ALTER TABLE "UserProfile"
  ADD COLUMN IF NOT EXISTS "badgeNumber" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "station" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "employeeId" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "institution" TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS "UserProfile_role_idx" ON "UserProfile"("role");
